### ISSUE TITLE
Using any instantSearch theme other than algolia throws an error

### ISSUE THREAD

**Issue by andyjamesn** [nuxt-community/algolia-module#50]
### Version

@nuxtjs/algolia: ^0.9.1
nuxt: 3.0.0-rc.3

### Steps to reproduce
```
algolia: {
    apiKey: "82913680b786acdb395702cbbe8ad805",
    applicationId: "JQ8RQBS5H4",
    instantSearch: {
      theme: "reset",
    },
  },
```

### What is Expected?
As per the docs https://algolia.nuxtjs.org/advanced/
"You can choose a theme from satelite, reset, and algolia. Check out setup docs [here](https://algolia.nuxtjs.org/advanced/'/setup#instantSearch.theme')"

### What is actually happening?
 ERROR  [@nuxtjs/algolia] Invalid theme: reset
 ERROR  [@nuxtjs/algolia] Invalid theme: satelite                                                                                                                                                                                    

Setup docs also goes to a broken link
https://algolia.nuxtjs.org/advanced/'/setup#instantSearch.theme'

**Comment by Baroshem** [comment]
Hi @andyjamesn 

Thanks for reporting that issue. I will take a look at it tomorrow and probably release a new version with a quick fix as it should not be something complicated 🙂

**Comment by Baroshem** [comment]
@andyjamesn 

I did some testing and in my case the algolia and satellite (check if you typed double `t` in the name, there is a typo in the docs), however it does not work for some reason with 'reset'. 

I mean, it is working because the styles are being reset but the error appears in the console for some reason. The error should appear if a selected theme is out of the scope of supported styling. 

```ts
          if (InstantSearchThemes[theme]) {
            nuxt.options.css.push(`instantsearch.css/themes/${theme}.css`)
          } else {
            console.error('`[@nuxtjs/algolia]` Invalid theme:', theme)
          }
```

While InstantSearchThemes is:

```ts
enum InstantSearchThemes {
  'reset',
  'algolia',
  'satellite',
}
```

So your 'reset'  should be in the scope of the themes.

Maybe @yassilah you will have some clue why this is like that.

In the meantime I will make some corrections to the docs for vue instantsearch

**Comment by yassilah** [comment]
Hey! Yes, I see why, `enum` uses the index as value and vice-versa, so `InstantSearchThemes.reset` is `'0'` which becomes `false` in the if statement. I'll fix that in your PR.

**Comment by Baroshem** [comment]
@andyjamesn 

The module should now work as expected. Thanks for rising this issue and thanks @yassilah for resolving the issue :)

**Comment by andyjamesn** [comment]
Excellent. Thanks guys! Time to add the reset theme so I can add my own styling with TailwindCSS :D
